cd /etc/openclash/rule_provider
wget https://raw.githubusercontent.com/yusuftutorial/clash/master/rule_provider/ads.yaml
wget https://raw.githubusercontent.com/yusuftutorial/clash/master/rule_provider/porn.yaml
wget https://raw.githubusercontent.com/yusuftutorial/clash/master/rule_provider/sosmed.yaml
wget https://raw.githubusercontent.com/yusuftutorial/clash/master/rule_provider/stream.yaml
wget https://raw.githubusercontent.com/yusuftutorial/clash/master/rule_provider/game.yaml
wget https://raw.githubusercontent.com/yusuftutorial/clash/master/rule_provider/olshop.yaml
wget https://raw.githubusercontent.com/yusuftutorial/clash/master/rule_provider/bank.yaml
wget https://raw.githubusercontent.com/yusuftutorial/clash/master/rule_provider/chat.yaml